run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unconvert
    - gocritic
    - gocyclo
    - gofumpt
    - revive
  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: cmd/
      linters:
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0